#libforest.so: rforest_internal.o rforest_funcC.o cuore.o lodge.o
#	cc  -fPIC -shared -o libforest.so rforest_internal.o rforest_funcC.o cuore.o lodge.o

automataC.o: automataC.c automataC.h Automaton.h
	cc -fPIC -c automataC.c






#rforest_funcC.o: rforest_funcC.c lodge.h cuore.h
#	cc -fPIC -c  rforest_funcC.c

clean:
	rm -f automataC.o 



